### ISSUE TITLE
Missing /api suffix in helper text 

### ISSUE THREAD

**Issue by ADAmint2019** [input-output-hk/jormungandr-nix#15] opened 2019-07-14 17:05 UTC
When running jormungandr 0.3.0 the helper text for CLI REST shows:
--  jcli rest v0 node stats get -h "http://127.0.0.1:8443/"
Leaving off the required api  -- should read:
-- jcli rest v0 node stats get -h "http://127.0.0.1:8443/api"

This is true for the other example as well.

**Comment by disassembler** [comment] 2019-07-29 13:01
duplicate of #18 Fix there resolved this as well.

**Closed** 2019-07-29 13:01 UTC
